### PR TITLE
Fix the react-router to work on Github Pages

### PR DESCRIPTION
**Pull request by JaakkoLipsanen**

### CODE REVIEW

**Comment by anttilip** [comment]
How does this work? I see that the index.html is renamed to 404.html. Does this have any side effects?

**Comment by JaakkoLipsanen** [comment]
The repository is renamed to evento, and thus the url is https://flai.xyz/evento/

I changed index.html to 404.html because index.html only mathces `/` where as 404.html basically matches `/*`. It's a bit hacky solution, but it works.

**Comment by anttilip** [comment]
Oh, totally missed that. I don't think this should be a long term solution. Maybe we should try to move api to `api.evento.herokuapp.com` and front to `evento.herokuapp.com`? But for now this is completely fine.

**Comment by JaakkoLipsanen** [comment]
Why?

**Comment by anttilip** [comment]
Well, like you said, this is a bit hacky solution and not very clean. And if our api and front is running on same server the wake up time does not cumulate.

**Comment by JaakkoLipsanen** [comment]
I think it's "hacky" solution in the sense that it is not supposed to be used like that, but I don't think it's hacky in the sense that we shouldn't use it. And since the only change is just having 404.html instead of index.html, I don't think it's very "unclean" either.

I think that running API and front-end on same server in heroku makes no sense. The setup would be be pretty hard (since our client and server are different repos) and we would have to create a web-server for the front-end which serves the index.html to the client. Also, if we are running the front-end in Github, we get two advantages: first of all, better URL (flai.xyz/evento instead of evento.herokuapp.com) and support to display a "waiting for server..." or something while the server is waking up on Heroku.

Imo this is a good long term solution

**Comment by anttilip** [comment]
Doesn't subdomains work like evento.flai.xyz/ ? Shouldn't it be possible? But sure, some kind of loading screen or waiting text is a benefit.  The current setup is fine for me, but still I don't think it is optimal. The configuration alone would be quite difficult and we do not have the time right now.

**Pull request merged**
